### PR TITLE
Feature latest ordering

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@ANikolova22 @Frensisbras @EmmaWoodONS we may be better of just going this way as there is only one conflicy

**Comment by EmmaWoodONS** [comment]
@LucyGwilliamAdmin IF I'm not looking at it wrong (which is entirely possible), doing it this way looks like it will get rid of the recent SDMX changes

**Comment by ANikolova22** [comment]
Not sure.... I don't see any conflicts stated?

**Comment by EmmaWoodONS** [comment]
It doesn't cause a conflict, but if you look at the files changed, a lot of series info that looks like SDMX disappears

**Comment by ANikolova22** [comment]
Yes, indeed :/

**Pull request closed without merging**
