### PR TITLE
12.3.1 metadata update

### PR DESCRIPTION
**Pull request by ONSBen**
12.3.1 metadata update due to new data. Minor formatting changes.

### CODE REVIEW

**Comment by ONSBen** [comment]
Reasons for fail unclear.

@norric1

**Comment by ONSBen** [comment]
Issue identified and fix attempted.

**Comment by Norric1Admin** [comment]
Looks fine - that's a WRAP!

**Comment by ONSBen** [comment]
That pun is wasted in closed pull requests.

**Comment by Norric1Admin** [comment]
It was trash anyway :D

**Pull request closed without merging**
