### PR TITLE
Get latest from develop

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@EmmaWoodONS @ANikolova22 @Frensisbras this is the differences between develop and the latest ordering feature branch (develop -> feature branch). As you can see there's a lot of conflicts, which is actually fine because I need a test case to be able to check my guidance. I may just need some clarification on which option is correct when it comes to resolving the conflict.

What are your thoughts?

**Comment by EmmaWoodONS** [comment]
@LucyGwilliamAdmin most of them are mine (3-1-1 and all the 16s), which just leave 3 others. Is it just a case of looking at the feature branch and at develop and saying which is the one we want to go live, or which bits of each we want to go live?

**Comment by ANikolova22** [comment]
I think the two within G6 are mine. I imagine what is on the feature branch should be the correct version as that's where I put the changes, but may need to double check!

**Comment by ANikolova22** [comment]
- 6-5-1 has been updated with new data on the live site since that feature branch was created, but there is no change in any ordering that I can see. So for that one keep what is on develop

- 6-3-2 - Ian pushed an update to develop this morning, so the correct version should also be develop for that one

On a different note, I remembered the main issue I had with the command line. I tried to merge my resolved feature branch to develop and it wasn't possible because of permissions issues. So what I did instead was to merge the latest of develop into my feature, preserving the key changes from the feature branch (by conflict resolution), and then I pushed that locally resolved feature branch to the online version on the repository. After that I attempted again to merge with develop in the usual way and it worked! Hope that makes sense...

**Pull request merged**
